### ISSUE TITLE
[Bug Report] Fix the issues of v0.1

### ISSUE THREAD

**Issue by generationmake** [107-systems/T07#4]
<a href="https://107-systems.org/"><img align="right" src="https://raw.githubusercontent.com/107-systems/.github/main/logo/107-systems.png" width="15%"></a>

### :bug: Bug Report

   - add hole for battery cable
   - add cut out for fuse of CyphalRobotController07/CAN in controller standoff
   - add cut out for power pole connector in motor cover
   - reduce size of motor cover by 0.5 or 1 mm to better slide into mainchassis
   - add cut out for motor shaft into motor cover
   - add cutout for motor connector into mainchassis
   - CyphalRobotController07/CAN collides with screws and nuts for holder for mandeye controller

**Comment by generationmake** [comment]
@aentinger 
did i miss something?

**Comment by aentinger** [comment]
>did i miss something?

No, I believe you did catch everything 😉

**Comment by generationmake** [comment]
- slightly increase top opening of mandeye controller holder to let mandeye controller slide in easier

**Comment by generationmake** [comment]
- imcrease hole for blade connector in einhell battery holder

**Comment by generationmake** [comment]
- add mounting hole for antenna?
  - add mounting holes for beaglebone black?

**Comment by generationmake** [comment]
A standard screw nut M6 (DIN 934) is 5 mm high. A self securing nut (DIN 985) is 6 mm high. A flat nut (DIN 439) is 3.2 mm high.
So I suggest using a flat nut and the right screws and there will be no collision with the controller board.
